github:
  prebuilds:
    master: false
    branches: false
tasks:
  - name: OB Standalone
    init: docker pull oceanbase/oceanbase-ce
    command: |
      echo "alias sh='/bin/bash'" >> ~/.profile
      source ~/.profile
      docker run -p 2881:2881 --name obstandalone -e MINI_MODE=1 -d oceanbase/oceanbase-ce
      bash /workspace/ob-example/tools/gitpod/init.sh
