server:
  port: 8081
spring:
  jpa:
    database: mysql # mysql, oracle
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:2881/test?characterEncoding=UTF-8
    username: root@test
    password:
#spring.jpa.hibernate.ddl-auto=update
jackson:
  serialization:
    indent_output: true

