name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.*'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.*'
concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  golang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ "go-sql-driver" ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set Go env
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Start docker container
        timeout-minutes: 5
        run: |
          docker run --name oceanbase-ce --network host -e MODE=slim -e FASTBOOT=true -d oceanbase/oceanbase-ce
          eval 'while ! docker logs oceanbase-ce | grep -q "boot success!"; do echo "booting..."; sleep 10; done'
          echo "boot success!"
      - name: Run example for ${{ matrix.module }}
        run: |
          cd ob-example-golang/${{ matrix.module }}
          sh run.sh

  java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ "mysql-connector-java", "oceanbase-client" ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Start docker container
        timeout-minutes: 5
        run: |
          docker run --name oceanbase-ce --network host -e MODE=slim -e FASTBOOT=true -d oceanbase/oceanbase-ce
          eval 'while ! docker logs oceanbase-ce | grep -q "boot success!"; do echo "booting..."; sleep 10; done'
          echo "boot success!"
      - name: Run example for ${{ matrix.module }}
        run: |
          cd ob-example-java/${{ matrix.module }}
          sh run.sh

  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ "pymysql" ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Start docker container
        timeout-minutes: 5
        run: |
          docker run --name oceanbase-ce --network host -e MODE=slim -e FASTBOOT=true -d oceanbase/oceanbase-ce
          eval 'while ! docker logs oceanbase-ce | grep -q "boot success!"; do echo "booting..."; sleep 10; done'
          echo "boot success!"
      - name: Run example for ${{ matrix.module }}
        run: |
          cd ob-example-python/${{ matrix.module }}
          sh run.sh
