name: CI
on: [ push, pull_request ]
concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ "mysql-connector-java", "oceanbase-client" ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Start docker container
        timeout-minutes: 5
        run: |
          docker run --name oceanbase-ce --network host -e MODE=slim -e FASTBOOT=true -d oceanbase/oceanbase-ce
          eval 'while ! docker logs oceanbase-ce | grep -q "boot success!"; do echo "booting..."; sleep 10; done'
          echo "boot success!"
      - name: Run example for ${{ matrix.module }}
        run: |
          cd ob-example-java/${{ matrix.module }}
          sh run.sh
