name: CI
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.*'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.*'

jobs:
  basic:
    strategy:
      matrix:
        module:
          - name: 'go-sql-driver'
            language: 'golang'
          - name: 'mysql-connector-java'
            language: 'java'
          - name: 'oceanbase-client'
            language: 'java'
          - name: 'testcontainers-java'
            language: 'java'
            with_oceanbase_container: false
          - name: 'pymysql'
            language: 'python'
          - name: 'mysql-connector-python'
            language: 'python'
    uses: ./.github/workflows/basic-ci.yml
    with:
      module: ${{ matrix.module.name }}
      language: ${{ matrix.module.language }}
      with_oceanbase_container: ${{ matrix.module.with_oceanbase_container || true }}
