name: Golang CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    paths: [ 'golang/**' ]

jobs:
  golang:
    strategy:
      matrix:
        module:
          - name: 'go-sql-driver'
            with_oceanbase_container: true
          - name: 'gorm'
            with_oceanbase_container: true
    uses: ./.github/workflows/basic-workflow.yml
    with:
      language: 'golang'
      module: ${{ matrix.module.name }}
      with_oceanbase_container: ${{ matrix.module.with_oceanbase_container }}
