name: Python CI

on:
  push:
    paths:
      - '.github/workflows/python.yml'
      - 'python/**'
  pull_request:
    paths:
      - '.github/workflows/python.yml'
      - 'python/**'

jobs:
  ci:
    strategy:
      matrix:
        module:
          - name: 'mysql-connector-python'
            with_oceanbase_container: true
          - name: 'pymysql'
            with_oceanbase_container: true
          - name: 'sqlalchemy'
            with_oceanbase_container: true
    uses: ./.github/workflows/basic-workflow.yml
    with:
      language: 'python'
      module: ${{ matrix.module.name }}
      with_oceanbase_container: ${{ matrix.module.with_oceanbase_container }}
